package lookupnames;

public enum LookUpNames {
    ONLINECONTROLLER,
    AUTHENTICATIONCONTROLLER,
    MESSAGECONTROLLER,
    USERPROFILECONTROLLER,
    GROUPCHATCONTROLLER,
    INVITATIONCONTROLLER,
    CONTACTCONTROLLER;
}
