package lookupnames;

//import dto.Controller.TrackOnlineUsers;

public enum LookUpNames {
    TRACKONLINEUSERS,
    SENDHEARTBEATTOSERVERFROMCLIENT,
    ONLINECONTROLLER,
    AUTHENTICATIONCONTROLLER,
    MESSAGECONTROLLER,
    USERPROFILECONTROLLER,
    GROUPCHATCONTROLLER,
    INVITATIONCONTROLLER,
    CONTACTCONTROLLER,
    VOICECHATCONTROLLER;


}
