package lookupnames;

public enum LookUpNames {
    TRACKONLINEUSERS,
    ONLINECONTROLLER,
    AUTHENTICATIONCONTROLLER,
    MESSAGECONTROLLER,
    USERPROFILECONTROLLER,
    GROUPCHATCONTROLLER,
    INVITATIONCONTROLLER,
    CONTACTCONTROLLER,
    VOICECHATCONTROLLER,
    BLOCKUSERCONTROLLER
}
