name: Merge Development into Prototyping

on:
  push:
    branches:
      - development

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure prototyping branch exists
      run: |
        if [ ! -d ".git/refs/heads/prototyping" ]; then
          git fetch origin prototyping:prototyping
        fi

    - name: Merge development into prototyping
      run: |
        git checkout prototyping
        git pull --rebase origin development  # Use rebase to avoid conflicts

        # Auto-resolve conflicts using "theirs" strategy
        git -c user.email="actions@github.com" -c user.name="GitHub Actions" \
          -c merge.conflictStyle=diff3 \
          -c merge.strategy=recursive -c merge.ours=HEAD -c merge.theirs=origin/development \
          rebase --skip

        git push origin prototyping
