name: Merge Development into Prototyping

on:
  push:
    branches:
      - development

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure prototyping branch exists
      run: |
        if [ ! -d ".git/refs/heads/prototyping" ]; then
          git fetch origin prototyping:prototyping
        fi

    - name: Merge development into prototyping
      run: |
        git checkout prototyping
        git pull origin development
        git merge --no-ff --no-commit origin/development  # Use --no-ff to preserve merge commit
        git checkout --theirs .  # Keep changes from development branch in case of conflicts
        git add .
        git commit -m "Merge development into prototyping"
        git push origin prototyping
