name: Merge Development into Prototyping

on:
  push:
    branches:
      - development

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git identity
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Ensure prototyping branch exists
      run: |
        if [ ! -d ".git/refs/heads/prototyping" ]; then
          git fetch origin prototyping:prototyping
        fi

    - name: Merge development into prototyping
      run: |
        git checkout prototyping
        git pull --no-rebase --no-ff --allow-unrelated-histories -s recursive -X theirs origin development
        git push origin prototyping
